version: '2.0'
services:
  backend:
    build: .
    command: ./main -port 3001
    environment:
      - MG_API_KEY
      - MG_DOMAIN
      - "https_proxy=http://x:${PROXY_PASS}@vaulty:8080"
    volumes:
      # demo app should have access to Vaulty's CA certificate
      # when we run command to add it to system certificates
      - "./vaulty/ca.cert:/app/ca.cert"

  vaulty:
    build:
      context: ../../vaulty
    # image: vaulty/vaulty
    command: ./vaulty proxy --debug -r /.vaulty/routes.json --ca /.vaulty
    ports:
      - "3001:8080"
    environment:
      - PROXY_PASS
      - ENCRYPTION_KEY
    links:
      - backend
    volumes:
      - "./vaulty:/.vaulty"
